### ISSUE TITLE
ModuleNotFoundError: No module named 'webots_drone'

### ISSUE THREAD

**Issue by DKKHerath** [angel-ayala/gym-webots-drone#1]
INFO: fire_movement: Starting controller: python.exe -u fire_movement.py 
INFO: drone_controller: Starting controller: python.exe -u drone_controller.py
INFO: 'agent' extern controller: Waiting for local or remote connection on port 1234 targeting robot named 'agent'.
Traceback (most recent call last):
  File "C:\WORKSPACE\Research\webots-drone\controllers\drone_controller\drone_controller.py", line 12, in <module>
    from drone import Drone
  File "C:\WORKSPACE\Research\webots-drone\controllers\drone_controller\drone.py", line 10, in <module>
    from webots_drone.utils import bytes2image
ModuleNotFoundError: No module named 'webots_drone'
WARNING: 'drone_controller' controller exited with status: 1.

**Comment by angel-ayala** [comment]
Hi, did you followed the [installation instructions](https://github.com/angel-ayala/gym-webots-drone?tab=readme-ov-file#installation-and-use) ?

**Comment by DKKHerath** [comment]
Hi , Sorry I was away, that fixed the error, now getting the below

C:\WORKSPACE\RESEARCH2\gym-webots-drone>
C:\WORKSPACE\RESEARCH2\gym-webots-drone>python webots_drone/webots_simulation.py
Traceback (most recent call last):
  File "C:\WORKSPACE\RESEARCH2\gym-webots-drone\webots_drone\webots_simulation.py", line 13, in <module>
    from webots_drone.utils import check_flight_area
  File "c:\workspace\research2\gym-webots-drone\webots_drone\__init__.py", line 7, in <module>
    from .webots_simulation import WebotsSimulation
  File "c:\workspace\research2\gym-webots-drone\webots_drone\webots_simulation.py", line 22, in <module>
    from controller import Supervisor
ImportError: cannot import name 'Supervisor' from 'controller' (C:\Users\<>\anaconda3\Lib\site-packages\controller\__init__.py)

**Comment by angel-ayala** [comment]
Have you defined the `WEBOTS_HOME` environment variable? check the [considerations](https://github.com/angel-ayala/gym-webots-drone?tab=readme-ov-file#considerations-of-the-environment)

**Comment by DKKHerath** [comment]
Hi, Is there a way to contact you?
Linked in, watsapp

**Comment by angel-ayala** [comment]
reasons?

**Comment by DKKHerath** [comment]
Hi I am stucked  with my MSc project. 

Need to train a drone using PPO with dynamic objects.
looking for support and I can pay for the effort 

Thank you

**Comment by angel-ayala** [comment]
email me with your background and project details at aaam@ecomp.poli.br maybe we can do some collaboration, be fast I will delete this comment

**Comment by DKKHerath** [comment]
Noted. please delete
